name: catpred_env
channels:
  - pytorch
  - conda-forge
  - pyg
dependencies:
  - conda-forge::python=3.9.23
  - conda-forge::matplotlib=3.9.4
  - conda-forge::numpy=1.26.4
  - conda-forge::pandas=2.3.1
  - conda-forge::pandas-flavor=0.7.0
  - conda-forge::pip=25.2
  - pytorch::pytorch=2.4.1=py3.9_cuda*
  - conda-forge::scikit-learn=1.6.1
  - conda-forge::scipy=1.13.1
  - conda-forge::tensorboardX=2.6.2.2
  - pytorch::torchvision=0.19.1
  - conda-forge::tqdm=4.67.1
  - pytorch::faiss-cpu=1.9.0
  - pyg::pytorch-scatter=2.1.2
  - pyg::pyg=2.6.1
  - kimlab::stride=1.6.4
  - conda-forge::transformers=4.57.6
  - conda-forge::ipdb=0.13.13
  - conda-forge::sentencepiece=0.2.1
  - conda-forge::seaborn=0.13.2
  - conda-forge::typed-argument-parser=1.11.0
  - pip:
    - fair-esm==2.0.0
    - progres==1.1.0
    - rdkit-pypi==2022.9.5
    - descriptastorus==2.8.0
    - rotary-embedding-torch==0.6.5